picoos-ow: 1-Wire API
1-Wire API
int ReadTemperature (int portnum, uchar *SerialNum, float *Temp)
SMALLINT owFirst (int portnum, SMALLINT do_reset, SMALLINT alarm_only)
SMALLINT owNext (int portnum, SMALLINT do_reset, SMALLINT alarm_only)
void owSerialNum (int portnum, uchar *serialnum_buf, SMALLINT do_read)
void owFamilySearchSetup (int portnum, SMALLINT search_family)
void owSkipFamily (int portnum)
SMALLINT owAccess (int portnum)
SMALLINT owVerify (int portnum, SMALLINT alarm_only)
SMALLINT owOverdriveAccess (int portnum)
SMALLINT bitacc (SMALLINT op, SMALLINT state, SMALLINT loc, uchar *buf)
Detailed Description
Function Documentation
SMALLINT bitacc (SMALLINT op, SMALLINT state, SMALLINT loc, uchar * buf)
Bit utility to read and write a bit in the buffer 'buf'.
Parameters
'op' - operation (1) to set and (0) to read
'state' - set (1) or clear (0) if operation is write (1)
'loc' - bit number location to read or write
'buf' - pointer to array of bytes that contains the bit to read or write
Returns
1 if operation is set (1) 0/1 state of bit number 'loc' if operation is reading
Referenced by owVerify().
SMALLINT owAccess (int portnum)
The 'owAccess' function resets the 1-Wire and sends a MATCH Serial Number command followed by the current SerialNum code. After this function is complete the 1-Wire device is ready to accept device-specific commands.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number.
Returns: TRUE (1) : reset indicates present and device is ready for commands. FALSE (0): reset does not indicate presence or echos 'writes' are not correct.
Referenced by ReadTemperature().
void owFamilySearchSetup (int portnum, SMALLINT search_family)
Setup the search algorithm to find a certain family of devices the next time a search function is called 'owNext'.
'portnum' - number 0 to MAX_PORTNUM-1. This number was provided to OpenCOM to indicate the port number. 'search_family' - family code type to set the search algorithm to find next.
SMALLINT owFirst (int portnum, SMALLINT do_reset, SMALLINT alarm_only)
The 'owFirst' finds the first device on the 1-Wire Net This function contains one parameter 'alarm_only'. When 'alarm_only' is TRUE (1) the find alarm command 0xEC is sent instead of the normal search command 0xF0. Using the find alarm command 0xEC will limit the search to only 1-Wire devices that are in an 'alarm' state.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number. 'do_reset' - TRUE (1) perform reset before search, FALSE (0) do not perform reset before search. 'alarm_only' - TRUE (1) the find alarm command 0xEC is sent instead of the normal search command 0xF0
Returns: TRUE (1) : when a 1-Wire device was found and it's Serial Number placed in the global SerialNum[portnum] FALSE (0): There are no devices on the 1-Wire Net.
References owNext().
SMALLINT owNext (int portnum, SMALLINT do_reset, SMALLINT alarm_only)
The 'owNext' function does a general search. This function continues from the previos search state. The search state can be reset by using the 'owFirst' function. This function contains one parameter 'alarm_only'. When 'alarm_only' is TRUE (1) the find alarm command 0xEC is sent instead of the normal search command 0xF0. Using the find alarm command 0xEC will limit the search to only 1-Wire devices that are in an 'alarm' state.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number. 'do_reset' - TRUE (1) perform reset before search, FALSE (0) do not perform reset before search. 'alarm_only' - TRUE (1) the find alarm command 0xEC is sent instead of the normal search command 0xF0
Returns: TRUE (1) : when a 1-Wire device was found and it's Serial Number placed in the global SerialNum[portnum] FALSE (0): when no new device was found. Either the last search was the last device or there are no devices on the 1-Wire Net.
Referenced by owFirst().
SMALLINT owOverdriveAccess (int portnum)
Perform a overdrive MATCH command to select the 1-Wire device with the address in the ID data register.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number.
Returns: TRUE: If the device is present on the 1-Wire Net and can do overdrive then the device is selected. FALSE: Device is not present or not capable of overdrive.
*Note: This function could be converted to send DS2480 commands in one packet.
void owSerialNum (int portnum, uchar * serialnum_buf, SMALLINT do_read)
The 'owSerialNum' function either reads or sets the SerialNum buffer that is used in the search functions 'owFirst' and 'owNext'. This function contains two parameters, 'serialnum_buf' is a pointer to a buffer provided by the caller. 'serialnum_buf' should point to an array of 8 unsigned chars. The second parameter is a flag called 'do_read' that is TRUE (1) if the operation is to read and FALSE (0) if the operation is to set the internal SerialNum buffer from the data in the provided buffer.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number. 'serialnum_buf' - buffer to that contains the serial number to set when do_read = FALSE (0) and buffer to get the serial number when do_read = TRUE (1). 'do_read' - flag to indicate reading (1) or setting (0) the current serial number.
Referenced by ReadTemperature().
void owSkipFamily (int portnum)
Set the current search state to skip the current family code.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number.
SMALLINT owVerify (int portnum, SMALLINT alarm_only)
The function 'owVerify' verifies that the current device is in contact with the 1-Wire Net. Using the find alarm command 0xEC will verify that the device is in contact with the 1-Wire Net and is in an 'alarm' state.
'portnum' - number 0 to MAX_PORTNUM-1. This number is provided to indicate the symbolic port number. 'alarm_only' - TRUE (1) the find alarm command 0xEC is sent instead of the normal search command 0xF0.
Returns: TRUE (1) : when the 1-Wire device was verified to be on the 1-Wire Net with alarm_only == FALSE or verified to be on the 1-Wire Net AND in an alarm state when alarm_only == TRUE. FALSE (0): the 1-Wire device was not on the 1-Wire Net or if alarm_only == TRUE, the device may be on the 1-Wire Net but in a non-alarm state.
References bitacc().
int ReadTemperature (int portnum, uchar * SerialNum, float * Temp)
Read the temperature of a DS1920/DS1820
'portnum' - number 0 to MAX_PORTNUM-1. This number was provided to OpenCOM to indicate the port number. 'SerialNum' - Serial Number of DS1920/DS1820 to read temperature from 'Temp ' - pointer to variable where that temperature will be returned
Returns: TRUE(1) temperature has been read and verified FALSE(0) could not read the temperature, perhaps device is not in contact
References owAccess(), and owSerialNum().